<?php

require_once '../GlobalFunctions/Validation.php';

class Create extends Validation
{
    public function filtraDados(): bool
    {
        return parent::filtraDados(); // TODO: Change the autogenerated stub
    }
    public function verificaVazios(): bool
    {
        return parent::verificaVazios(); // TODO: Change the autogenerated stub
    }
    public function entradaDeDados(): bool
    {
        return parent::entradaDeDados(); // TODO: Change the autogenerated stub
    }


    // MENSAGEM DE FEEDBACK DE ACORDO COM O ID (CADA ID É UMA MENSAGEM DIFERENTE)
    public function msgFeedback()
    {
        global $msgsucesso;
        $id = filter_input(INPUT_GET, "id", FILTER_SANITIZE_NUMBER_INT); // Filtrar o ID como um número inteiro
        switch ($id) {
            case 6:
                $msgsucesso = "Cadastro não realizado"; //CADASTRO
                break;
            case 1:
                $msgsucesso = "Cadastro realizado";
                break;
            case 2:
                $msgsucesso = "Houve um erro ao editar o usuario"; //EDITAR
                break;
            case 3:
                $msgsucesso = "Usuario editado com Sucesso";
                break;
            case 4:
                $msgsucesso = "Houve um erro ao deletar o usuario"; //DELETAR
                break;
            case 5:
                $msgsucesso = "Usuario deletado com sucesso";
                break;
            default:
                $msgsucesso = ""; //DEFAULT
                break;
        }

    }

    // COMEÇO DO CODIGO DE CADASTRO
    public function cadastrarDados()
    {
        try {
            if ($this->entradaDeDados() && $this->verificaVazios()) {
                $PDO = new PDO("mysql:host=localhost;dbname=bancoaula", "root", "");
                $nome = filter_input(INPUT_POST, 'nome-input', FILTER_SANITIZE_SPECIAL_CHARS);
                $email = filter_input(INPUT_POST,'email-input');
                $senha = sha1(filter_input(INPUT_POST, 'senha-input'));
                $sql = "INSERT INTO usuarios1 (id, nome, email, senha) VALUES (NULL, :nome, :email, :senha)";
                $resultado = $PDO->prepare($sql);
                $resultado->bindParam(':nome', $nome);
                $resultado->bindParam(':email', $email);
                $resultado->bindParam(':senha', $senha);

            if ($resultado->execute()) {
                header("Location: ../Views/CreateWeb.php?id=1");
                exit();
            } else {
                header("Location: ../Views/CreateWeb.php?id=6");
                exit();
            }
        }}

        catch (PDOException $ex) {
            error_log($ex->getMessage());
            header("Location: ../Views/CreateWeb.php?id=6");
            exit();
        }
    }
}
